IPMS.Web/Controllers/ApiDataController.cs
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using IPMS.Web.Models;
using IPMS.Web.Models.Config;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace IPMS.Web.Controllers
{
    [AllowAnonymous]
    public class ApiDataController : BaseController
    {
        public ApiDataController(IOptions<ApiConfig> configAccessor,
            IHttpClientFactory clientFactory)
            : base(configAccessor, clientFactory)
        {
        }


        [HttpGet]
        public async Task<IActionResult> GetCategories()
        {
            try
            {
                var response = await _httpClient.GetAsync("category");
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<CategoryViewModel>(responseBody);

                var data = result.data;

                var obj = data.Select(x => new { id = x.CategoryId, name = x.CategoryName })
                    .ToList();

                return Ok(obj);
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetBrands(int categoryId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"brand/?categoryId={categoryId}");
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<BrandViewModel>(responseBody);

                var data = result.data;

                var obj = data.Select(x => new { id = x.BrandId, name = x.BrandName })
                    .ToList();

                return Ok(obj);
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetSizes(int brandId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"size/?brandId={brandId}");
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<SizeViewModel>(responseBody);

                var data = result.data;

                var obj = data.Select(x => new { id = x.SizeId, name = x.SizeName })
                    .ToList();

                return Ok(obj);
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetWeights(int sizeId)
        {
            try
            {
                var response = await _httpClient.GetAsync($"weight/?sizeId={sizeId}");
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<WeightViewModel>(responseBody);

                var data = result.data;

                var obj = data.Select(x => new { id = x.WeightId, name = x.WeightName })
                    .ToList();

                return Ok(obj);
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

IPMS.Web/Controllers/WeightController.cs
using System;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;
using IPMS.Web.Models;
using IPMS.Web.Models.Config;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace IPMS.Web.Controllers
{
    [AllowAnonymous]
    public class WeightController : BaseController
    {
        public WeightController(IOptions<ApiConfig> configAccessor,
           IHttpClientFactory clientFactory)
           : base(configAccessor, clientFactory)
        {
        }
        [HttpGet("/weight/list")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetWeights()
        {
            var response = await _httpClient.GetAsync("weight/");
            response.EnsureSuccessStatusCode();
            string responseBody = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<WeightViewModel>(responseBody);
            var categories = result.data;

            var obj = new
            {
                recordsTotal = 0,
                recordsFiltered = 10,
                data = (from item in categories
                        select new string[]
                        {
                            item.WeightName,
                            item.WeightIsActive.ToString(),
                            item.WeightId.ToString()
                        }).ToArray()
            };

            return Json(obj);
        }

        [HttpGet]
        [Route("/weight/add")]
        public IActionResult Add()
        {
            var model = new WeightModel();

            return View(model);
        }

        [HttpPost]
        //[Route("/weight/add")]
        public async Task<IActionResult> Add(WeightModel model)
        {
            try
            {
                var json = JsonConvert.SerializeObject(model);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsJsonAsync(
                    "weight", model);
                response.EnsureSuccessStatusCode();

                string responseBody = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<WeightViewModel>(responseBody);

                if (result.success == "true")
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }

            return View();
        }
    }
}

IPMS.Web/Views/Weight/Add.cshtml
@using IPMS.Web.Models

@model WeightModel

@{

    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}



<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="min-height: 264px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Weight</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Weight" asp-action="Index">Weight List</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">


            <div class="row">
                <div class="col-md-10">

                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Add Weight</h3>
                        </div>
                        <form class="form" method="post" asp-controller="Weight" asp-action="Add">
                            <div class="card-body">

                                <div class="form-group">
                                    <label>Category</label>
                                    <select class="form-control" id="category">
                                        <option selected="selected">- Select -</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Brand</label>
                                    <select class="form-control" id="brand">
                                        <option selected="selected">- Select -</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Size</label>
                                    <select asp-for="SizeId" class="form-control" id="size">
                                        <option selected="selected">- Select -</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Weight Name</label>
                                    <input asp-for="WeightName" type="text" class="form-control my-colorpicker1 colorpicker-element" placeholder="" title="">
                                </div>
                            </div>

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            <!-- /.card-body -->


                        </form>
                    </div>
                </div>
            </div>


        </div>
    </section>
</div>

@section Scripts
{
    <script type="text/javascript">

        $(document).ready(function () {

            $.ajax({
                url: '@Url.Action("GetCategories", "ApiData")',
                type: 'get',
                dataType: 'json',
                success: function (response) {

                    var len = response.length;

                    for (var i = 0; i < len; i++) {
                        var id = response[i]['id'];
                        var name = response[i]['name'];

                        $("#category").append("<option value='" + id + "'>" + name + "</option>");

                    }
                }
            });

            $('#category').change(function () {
                var categoryId = $(this).val();

                    $.ajax({
                    url: '@Url.Action("GetBrands", "ApiData")',
                    type: 'get',
                    dataType: 'json',
                    data: { categoryId: categoryId },
                    success: function (response) {

                        var len = response.length;

                        $("#brand").empty();
                        $("#brand").append("<option selected=\"selected\">- Select -</option>");

                        for (var i = 0; i < len; i++) {
                            var id = response[i]['id'];
                            var name = response[i]['name'];

                            $("#brand").append("<option value='" + id + "'>" + name + "</option>");

                        }
                    }
                });
            });

             $('#brand').change(function () {
                var brandId = $(this).val();

                    $.ajax({
                    url: '@Url.Action("GetSizes", "ApiData")',
                    type: 'get',
                        dataType: 'json',
                        data: { brandId: brandId },
                    success: function (response) {

                        var len = response.length;

                        $("#size").empty();
                        $("#size").append("<option selected=\"selected\">- Select -</option>");

                        for (var i = 0; i < len; i++) {
                            var id = response[i]['id'];
                            var name = response[i]['name'];

                            $("#size").append("<option value='" + id + "'>" + name + "</option>");

                        }
                    }
                });
            });

        })

    </script>
}

IPMS.Web/Views/Weight/Index.cshtml
@model IPMS.Web.Models.WeightModel

@{

    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}


@section PageStyles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Admin-LTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Weight List</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a asp-controller="Weight" asp-action="Add">Add Weight</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        @*<partial name="_ActionMessage" model="@Model.Response" />*@
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Weight Name</th>
                                    <th>Is Active</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Weight Name</th>
                                    <th>Is Active</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/admin/books/deletebook" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section Scripts
{
    <!-- DataTables -->
    <script src="~/Admin-LTE/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/Admin-LTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#example1').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Weight/GetWeights",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 2,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/books/editbook/${data}'" value='${data}'>
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </button>
                                        <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </button>`;
                        }
                    }
                ]
            });

            $('#example1').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}